### ISSUE TITLE
[BUILD] 프로젝트 마이그레이션 및 개선

### ISSUE THREAD

**Issue by hakilee** [hufsdevelopers/calguksu-frontend#11]
## TODO
빌드 효율화 및 공통 컴포넌트 분리를 위해 `yarn classic` 패키지 매니저로 구현된 칼국수 프론트엔드를 `pnpm`과 `turborepo`로 마이그레이션 합니다.

- [ ] `pnpm` + `turborepo` 마이그레이션
- [ ] `eslint` 맟 `prettier` 설정
- [ ] 공통 컴포넌트 및 스타일 분리
- [ ] 구현된 프로젝트 코드 및 함수 정리
